spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
  graphql:
    jpa:
      query:
        name: GraphQLJpaQueryOraliaSystem
        description: GraphQL Jpa Query Oralia System
        enabled: true
graphql:
  servlet:
    corsEnabled: false
    mapping: /graphql
    multipart:
      enabled: true
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
server:
  port: 8081
graphiql:
  enabled: true

file:
  upload-dir=: /uploads

security:
  basic:
    enable: false

management:
  security:
    enable: false



